---
- name: Update Arch Linux Machines
  hosts: arch_servers
  become: yes
  tasks:
    - name: Update pacman package manager cache
      pacman:
        update_cache: yes

    - name: Upgrade all packages
      pacman:
        upgrade: yes
        update_cache: yes
      register: upgrade_result

    - name: Clean up orphaned packages
      shell: "pacman -Rns $(pacman -Qtdq) || echo 'No orphans to remove'"
      register: cleanup_result
      failed_when: false

    - name: Check if reboot is required
      shell: "checkupdates | grep -E 'kernel|linux'"
      register: reboot_required
      failed_when: false

    - name: Reboot if the kernel was upgraded
      reboot:
      when: reboot_required.stdout != ""
