---
- name: Update and Cleanup Arch Linux with pacman and yay
  hosts: archlinux
  become: yes

  tasks:
    - name: Update pacman package database
      pacman:
        update_cache: yes

    - name: Upgrade all packages with pacman
      pacman:
        upgrade: yes

    - name: Check for orphaned packages with pacman
      command: pacman -Qdtq
      register: orphaned_packages
      ignore_errors: yes

    - name: Remove unnecessary packages with pacman
      command: pacman -Rns {{ orphaned_packages.stdout_lines }} --noconfirm
      when: orphaned_packages.stdout != ""

    - name: Clean up pacman cache
      command: paccache -r

    - name: Ensure yay is installed
      pacman:
        name: yay
        state: present

    - name: Update AUR packages with yay
      command: yay -Syu --noconfirm
      environment:
        LC_ALL: C

    - name: Check for orphaned packages with yay
      command: yay -Qdtq
      register: yay_orphaned_packages
      ignore_errors: yes

    - name: Remove orphaned packages with yay
      command: yay -Rns {{ yay_orphaned_packages.stdout_lines }} --noconfirm
      when: yay_orphaned_packages.stdout != ""

    - name: Clean up yay cache
      command: yay -Sc --noconfirm
