---
- name: Update and Cleanup Arch Linux with pacman and yay
  hosts: archlinux
  become: yes

  tasks:
    - name: Update pacman package database
      pacman:
        update_cache: yes

    - name: Upgrade all packages with pacman
      pacman:
        upgrade: yes

    - name: Remove unnecessary packages with pacman
      pacman:
        name: "*"
        state: latest
        extra_args: "--noconfirm -Rns $(pacman -Qdtq)"

    - name: Clean up pacman cache
      command: paccache -r

    - name: Ensure yay is installed
      pacman:
        name: yay
        state: present

    - name: Update AUR packages with yay
      command: yay -Syu --noconfirm
      environment:
        LC_ALL: C

    - name: Remove orphaned packages with yay
      command: yay -Rns $(yay -Qdtq) --noconfirm
      when: "(yay -Qdtq | length) > 0"

    - name: Clean up yay cache
      command: yay -Sc --noconfirm
