---
- name: Update, clean, and maintain CentOS hosts
  hosts: Linux
  become: true
  vars:
    package_manager: yum  # Can be changed to dnf if needed
    update_options: "yes" # Additional options for update/upgrade tasks
    restart_vm: false     # Default to false, will be overridden by CLI argument if needed
  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      yum:
        name: '*'
        state: latest

    - name: Remove unnecessary packages
      yum:
        name: '*'
        state: absent
        autoremove: yes

    - name: Clean yum cache
      command: yum clean all

    - name: Restart the VM if needed
      command: /sbin/shutdown -r now
      when: restart_vm | bool and not ansible_check_mode
      async: 1
      poll: 0
