---
- name: Update, upgrade, clean and reboot Debian-based system if needed
  hosts: your_hosts_group
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
      register: upgrade_result

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Autoclean the package cache
      apt:
        autoclean: yes

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if needed
      reboot:
      when: reboot_required.stat.exists
